server:
  port: 8081

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/accesscontrolsystem
    username: Kole
    password: workit
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.access.entity